### PR TITLE
BU-21: Use direct MB database access for event and place entity

### PR DESCRIPTION
**Pull request by rsh7**
Add more entities files so that all the entities using MusicBrainz database can be imported directly from BrainzUtils for use in all Brainz projects.

### CODE REVIEW

**Comment by paramsingh** [comment]
@rsh7, tests seem to be failing.

**Comment by rsh7** [comment]
Yeah, I am yet to update some files. Adding the WIP tag.

**Comment by paramsingh** [comment]
Is this still WIP?

**Comment by rsh7** [comment]
> Is this still WIP?
Not now. :)

**Comment by amCap1712** [comment]
@alastair, #29 seems to have added this functionality already. We can probably close this without merging.

**Comment by alastair** [comment]
These changes were already merged in a separate PR

**Pull request closed without merging**
