### PR TITLE
Remove containers after tests complete

### PR DESCRIPTION
**Pull request by amCap1712**
Leaving containers up after tests is annoying and consumes memory unnecessarily so remove those after tests have run. Also, Take care to exit with correct code after removing containers.

### CODE REVIEW

**Comment by amCap1712** [comment]
Tested locally by adding a failing test and ensuring return code was non-zero.

**Comment by alastair** [comment]
This looks OK, but it does have the effect of making repetitive tests take longer (as it means that the db needs to start up and shut down each time). Perhaps we should eventually replace it with something like the test.sh we have in LB (which allows you to bring up test containers once manually, and then take them down when you're done).

**Comment by alastair** [comment]
@amCap1712 I've updated the test script to copy the LB style, if the CI tests succeed then we can go ahead and merge this.

**Comment by alastair** [comment]
ah, looks like we run the build/test steps manually in order to publish the results file, so everything works with CI, looks good to me.

**Pull request merged**
