### PR TITLE
BU-29: Use cache namespaces in ratelimit module

### PR DESCRIPTION
**Pull request by amCap1712**
BU-29
Instead of manually prefixing `rate-limit`, we utilise the namespace feature to do that.

### CODE REVIEW

**Comment by alastair** [comment]
This looks good.

While looking through livegrep, it seems like LB is still using its own rate limit module, is that right? 
I think what happened was we put it in LB first, then abstracted it here, then added this one to AB.

Please open a ticket or start work on moving LB's rate limiting to this module.

**Comment by amCap1712** [comment]
I checked and LB is indeed using its own ratelimit solution. I'll start work to make it use the BU module instead.

**Comment by amCap1712** [comment]
https://github.com/metabrainz/listenbrainz-server/pull/1290 migrates LB to BU ratelimiting module.

**Comment by alastair** [comment]
Does this need to be updated to include changes in #54?

**Pull request merged**
