### PR TITLE
BU-24: Change function definitions in artist.py, release.py in musicbrainz_db module

### PR DESCRIPTION
**Pull request by amCap1712**
BU-24, supersedes #25. 
I think renaming get_artist_by_id to get_artist_by_mbid is fine but that'll require changes in dowstream projects as well. I do not see the need of adding a `get_many_artist_by_mbid` function because `fetch_multiple_artists` already exists.

### CODE REVIEW

**Comment by alastair** [comment]
While we're going with the 2.0 release of BU let's also rename the methods to be consistent, so that they all end in `by_mbid`. Are we happy with the `fetch_multiple_x` methods? or do we want to rename it? Last chance until 3.0!

Also, are we happy with the default of the unknown_entities_for_missing to be False? (raises exception by default). Or alternatively, should we get rid of this functionality? I think it's only used in CB-408

**Comment by alastair** [comment]
We decided that with [CB-408](https://tickets.metabrainz.org/browse/CB-408) that we were going to remove support to show dummy page on CB. This is the only use of the `unknown_entities_for_missing` flag, so we decided that we would remove it from here and raise an exception by default if the item doesn't exist.

In BU-37 we proposed to not raise an exception in the bulk methods, and just skip returning data if it doesn't exist

**Comment by alastair** [comment]
@amCap1712 the returned items from these methods looks like this:
```
{
            "id": "f59c5520-5f46-4d2c-b2c4-822eabf53419",
            "name": "Linkin Park",
            "sort_name": "Linkin Park",
            "type": "Group",
        }
```
Maybe while we're here we should rename id->mbid too. What do you think?

**Comment by amCap1712** [comment]
Sure, using `mbid` seems good to me.

**Comment by alastair** [comment]
I've updated this to perform the following changes:
 * remove unknown_entities_for_missing parameter. Don't return dummy objects, and don't raise an exception if a requested item doesn't exist in the bulk lookup
 * rename all methods to get_x_by_mbid
 * return an 'mbid' key in all data instead of 'id'

**Comment by amCap1712** [comment]
Looks good! Thanks!

**Pull request merged**
