### PR TITLE
License brainzutils under GPL2

### PR DESCRIPTION
**Pull request by paramsingh**

### CODE REVIEW

**Comment by paramsingh** [comment]
I'll keep this unmerged for some time to let people speak up in case anyone has any problems with this.

**Comment by Freso** [comment]
Based on https://github.com/metabrainz/brainzutils-python/graphs/contributors you should ideally get sign-offs from @kartikeyaSh and @rsh7 (not sure how copyright works in relation to GSoC, but I'm guessing students don't handover their copyrights) and @alastair and @jflory7.

**Comment by alastair** [comment]
No problem from me for my contributions.

**Comment by kartikeyaSh** [comment]
I don't have any problems with my contributions.

**Comment by paramsingh** [comment]
OK, that should be good enough as gentlecat's contributions were already (C) MetaBrainz, I would think.

**Pull request merged**
